### ISSUE TITLE
Index out of Range

### ISSUE THREAD

**Issue by lbarberiscanoni** [skozilla/BoxOfficeMojo#2]
Hey!

Let me first start by saying that this library is epic! It solves one of the biggest issues out there for data gathering when it comes to movies, so thank you so much for making this!

I keep getting
`table = center[0].find("table")`
`IndexError: list index out of range`

The actual output is this
`Error parsing movie:  Inception (2010) - Box Office Mojo
Traceback (most recent call last):
  File "surf.py", line 7, in <module>
    movie = box_office_mojo.get_movie_summary("inception")
  File "<string>", line 2, in get_movie_summary
  File "/Users/lbarberiscanoni/Lorenzo/Github/movieScraper/boxofficemojoAPI/utils.py", line 36, in catch_connection_error
    return func(*args)
  File "/Users/lbarberiscanoni/Lorenzo/Github/movieScraper/boxofficemojoAPI/boxofficemojo.py", line 91, in get_movie_summary
    return movie.Movie(soup)
  File "/Users/lbarberiscanoni/Lorenzo/Github/movieScraper/boxofficemojoAPI/movie.py", line 16, in __init__
    MovieBase.__init__(self, html_soup)
  File "/Users/lbarberiscanoni/Lorenzo/Github/movieScraper/boxofficemojoAPI/base.py", line 17, in __init__
    self.extract_data()
  File "/Users/lbarberiscanoni/Lorenzo/Github/movieScraper/boxofficemojoAPI/movie.py", line 28, in extract_data
    table = center[0].find("table")
IndexError: list index out of range`

I tried with both Titanic as well as with Inception but the error persists.

**Comment by skozilla** [comment]
Hey @lbarberiscanoni,

I haven't worked on this repo in a while as you can see. I've been meaning to refactor it and solve some issues regarding BOM servers refusing to handle requests after issuing too many requests in a short amount time. However i never found the time to do so. As such, i can't help you with the code at this time.
